### ISSUE TITLE
Remove unused columns from users and scores

### ISSUE THREAD

**Issue by gregoryjpark** [gregoryjpark/threegoodthings#203]
After #202, remove these columns:

From `users` 
- has_reminder
- reminder_time
- reminder_timezone
- phone_number_area
- phone_number_exchange
- phone_number_line

From `scores`
- spn_pos
- spn_neg
- spn_good
- spn_bad
- spn_plsnt
- spn_unplsnt
- spn_happy
- spn_sad
- spn_afraid
- spn_joyful
- spn_angry
- spn_contented
- spane_score
- swl_1
- swl_2
- swl_3
- swl_4
- swl_5
- swl_total
- spane_p
- spane_n
- swl_day

#### TODO
- [x] merge and deploy changes in `second-week-cqc`
- [x] run migration to create `phone_numbers` table
- [x] run rake task to backfill phone numbers from user fields to `phone_numbers`
- [x] manually check phone numbers of existing users
- [ ] run migrations to remove fields listed above
